### ISSUE TITLE
你这个readme怎么跟MVVMHabit写的好相似，，，

### ISSUE THREAD

**Issue by hegaojian** [wzqjava/MVVMSmart#20]

**Comment by wzqjava** [comment]
ReadMe,Git fork 改造的的，里面都是用大家经常用的第三方，集合到一起，方便大家快速开发的

**Comment by wzqjava** [comment]
只不过smart里面用的是Jetpack架构组件的技术

**Comment by hegaojian** [comment]
啊，看到了，确实不一样，只是文档太相似了而已

**Comment by fengtech** [comment]
readme中提到的一些文件找不到，比如ToolbarViewModel等

**Comment by wzqjava** [comment]
恩,as3.6.2之前的几个版本有bug, ToolbarViewModel对应的布局使用include导入, UI中直接拿到标题中的控件代码会报红,但是不影响运行, 许多人反馈看着不舒服,我2020.04.26修改代码去除ToolbarViewModel,现在这版的标题是比较简洁也好理解的. 文档打算今天(2020.0428)更新
