### ISSUE TITLE
ViewModel父类中没有看到 startActivity()

### ISSUE THREAD

**Issue by fengtech** [wzqjava/MVVMSmart#24]
readme中这样描述,是不是不准确?
BaseViewModelMVVM与BaseFragmentMVVM通过StateLiveData来处理常用UI逻辑，即可在ViewModel中使用父类的showDialog()、startActivity()等方法。在这个MultiRecycleViewModel中就可以尽情的写你的逻辑了！

**Comment by wzqjava** [comment]
1 Java版的readme和kotlin的已经分开了
2 showDialog() 已经用rxjava封装了,请求网络自动调用,(showLoading不建议在viewmode中直接调用,viewmodel不持有UI层的引用)
3.startActivity() 建议在UI层来处理,属于UI层的东西, 写在viewmodel中,团队成员可能不好维护
建议多查看kotlin分支
多谢您的建议
