### ISSUE TITLE
这是mvvmhabit的翻译版么？

### ISSUE THREAD

**Issue by KupoGu** [wzqjava/MVVMSmart#26]

**Comment by fengtech** [comment]
比Habit更加简洁，更加稳定

**Comment by KupoGu** [comment]
ViewModeProvider改成factory 初始化呢，借鉴下，用反射么？

**Comment by wzqjava** [comment]
列表和文档风格相同而已,看你自己各取所需吧.
Lifecycles+Navigation+DataBinding+LiveData+loading封装+kotlin语言+java语言两个分支, 这些都是smart的功能.
Okhttp+Retrofit+RxJava+Glide(都是网络三把刀,网络框架完全不是一个东西,smart的baseUrl动态管理, 渠道配置,loading功能,签名配置,打包配置,MMKV等都是独有的,网络的封装不是一个套路)
根据自己感兴趣的技术进行学习吧

**Comment by KupoGu** [comment]
此框架是kotlin 的，为啥三把刀不用协程实现呢，rxjava 可以是时候摈弃了

**Comment by wzqjava** [comment]
协程很好,考虑以后慢慢支持. 很多开发者不太会协程, 协程引入后,想改造,改不动,就不敢引入了, 就失去Smart简单易用原则了, 以后考虑支持,多谢您的建议.
