### ISSUE TITLE
最近想换MVVM，看了下项目提一点需求或建议

### ISSUE THREAD

**Issue by hloong** [wzqjava/MVVMSmart#34]
1，有些项目的接口有多种不同的返回格式，而且并不统一，这很无奈，
   最好是能加一个接口方法把服务器返回的最原始数据抛出，能兼顾不同

  2，请求好像没有post的示例，POST能兼顾From表单和json提交么，可以设置一个提交类型，同一个框架里不同的接口可能一个用表单，一个用json提交

 3，注意到net_utils里面有个gsontypeadapter，为何不把BooleanType和StringType加上
 服务器返回的Boolean值和String也有null的，有时候碰到很多各种类型都返回null的接口，解析报错
 
4，暗黑模式，或者说换皮肤的功能有没有规划在里面，如果没有单独加上会不会难搞？

5，注意到项目里有不少java代码，是以后全转成kotlin还是一直保持java和kotlin共存？

6，项目后期会引入ARouter规划组件化么？

**Comment by wzqjava** [comment]
2: 已经添加post示例
4: 暗黑模式,开发者单独在app里加比较好
5:目前kotlin分支只有网络框架是java语言(方便初中级开发者引入后修改功能),两者完全互通的,kotlin使用更广泛了可以考虑都转成kotlin(转换很快的),网络框架看不懂的话,许多人不敢用的.
6: mvvmSmart作为基础框架, 与Arouter没有任何冲突,直接在你的其他组件里配置Arouter使用即可,本公司项目就是Arouter多组件的, 那个组件想使用Smart,依赖即可.
1和3可以考虑优化,3的建议优化很快的.需要给你个github授权吗
多谢您的建议

**Comment by hloong** [comment]
不客气，因为准备把项目升级mvvm，所以正好看到这个了，github开源项目其实不需要授权，如果有人想提交代码，直接fork一下到自己分支然后push到你那边，你就看到提交的代码，然后再决定是否合并的主分支上

**Comment by wzqjava** [comment]
好的,多谢
&nbsp;

&nbsp; &nbsp; &nbsp;顺祝工作顺利，生活愉快！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 王志强：15601326781 .


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hloong"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 上午10:39
收件人: "wzqjava/MVVMSmart"<MVVMSmart@noreply.github.com&gt;; 
抄送: "316301354"<316301354@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [wzqjava/MVVMSmart] 最近想换MVVM，看了下项目提一点需求或建议 (#34)





 
不客气，因为准备把项目升级mvvm，所以正好看到这个了，github开源项目其实不需要授权，如果有人想提交代码，直接fork一下到自己分支然后push到你那边，你就看到提交的代码，然后再决定是否合并的主分支上
