### ISSUE TITLE
Navigation 退栈重建的问题

### ISSUE THREAD

**Issue by Quyunshuo** [wzqjava/MVVMSmart#42]
关于使用 Navigation fragment 退栈返回到上一 fragment 时，页面重建的问题，感觉这样会影响正常的生命周期监听和一些业务逻辑，有什么好的解决方案吗

**Comment by wzqjava** [comment]
框架里已经解决了, 看下Fragment的base层



&nbsp; &nbsp; &nbsp;顺祝工作顺利，生活愉快！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 王志强：15601326781 .


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wzqjava/MVVMSmart"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 晚上6:37
收件人:&nbsp;"wzqjava/MVVMSmart"<MVVMSmart@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wzqjava/MVVMSmart] Navigation 退栈重建的问题 (#42)





 
关于使用 Navigation fragment 退栈返回到上一 fragment 时，页面重建的问题，感觉这样会影响正常的生命周期监听和一些业务逻辑，有什么好的解决方案吗

**Comment by Quyunshuo** [comment]
好的  谢谢
